name: Build Jekyll site to GitHub Pages

on:
  push:
    # Set skip branch -> main
    branches-ignore:
      - main

jobs:
  jekyll_publish_v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Standard usage
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          # Specify the Jekyll source location as a parameter
          jekyll_src: "sample_site"
          # Set action only build event
          build_only: true
